#!/bin/bash

function usage()
{
    cat << EOUSAGE
Usage: send-file-to [options] SERVER_NAME FILE1 [FILE2 ..]
       -f FOLDER: specify server folder to store files
       -u USER: specify server user
       -p PORT: specify server port
       -n : don't try remove files of same name on server before transfer
EOUSAGE
}

# Name-to-ip mapping file
THIS_FOLDER="${0%/*}"
source "${THIS_FOLDER}/func/utility.func"

TARGET_PATH=""
SERVER_USER=""
SERVER_PORT=""
declare -i BANDWIDTH_LIMIT=0
declare -i DELETE_BEFORE_CP=1

while getopts ":f:u:p:l:n" opt
do
    case ${opt} in
        f ) TARGET_PATH="${OPTARG}"
            ;;
        u ) SERVER_USER="${OPTARG}"
            ;;
        p ) SERVER_PORT="${OPTARG}"
            ;;
        l ) BANDWIDTH_LIMIT="${OPTARG}"
            ;;
        n ) DELETE_BEFORE_CP=0
            ;;
        ? ) usage
            exit 1
            ;;
    esac
done
shift $((${OPTIND} - 1))

SERVER_NAME=${1}
shift 1

# Get server user name and IP
SERVER_META=`getServerMeta "d${THIS_FOLDER}" "n${SERVER_NAME}" "u${SERVER_USER}" "p${SERVER_PORT}"`
if [ "${SERVER_META}" == "" ]; then
    echo "[ERROR] Unknown server or wrong parameters."
    exit 1
fi

# Check parameters
if [ ${#} -eq 0 ]; then
    echo "[ERROR] Please specify file to transfer."
    exit 1
fi

# If TARGET_PATH not specified, set it to user's home folder
if [ "${TARGET_PATH}" == "" ]; then
    SERVER_USER_PORT="${SERVER_META#*\ }"
    SERVER_IP="${SERVER_META##*@}"
    USE_PUB_KEY=$(echo "${SERVER_USER_PORT}" | grep "\-i ")
    if [ "${USE_PUB_KEY}" != "" ]; then
        SERVER_USER=$(echo "${SERVER_USER_PORT}" | sed 's#^.* \([^@]*\)@.*$#\1#g')
        PUBLIC_KEY=$(echo "${SERVER_USER_PORT}" | sed 's#^.*\(-i [^ ]*\) .*$#\1#g')
    else
        SERVER_USER="${SERVER_USER_PORT%@*}"
    fi
    if [ "${SERVER_USER}" == "root" ]; then
        TARGET_PATH="/root/"
    else
        TARGET_PATH="/home/${SERVER_USER}/"
    fi
fi

# If TARGET_PATH is not end with a '/', attach one
TARGET_PATH="${TARGET_PATH%/}/"

# Generate file list
FILE_DEL_LIST=""
FILE_SEND_LIST=""
for FILE in $@; do
    FILE_DEL_LIST="${TARGET_PATH}${FILE##*/} ${FILE_DEL_LIST}"
    FILE_SEND_LIST="${FILE} ${FILE_SEND_LIST}"
done

# If set bandwidth limit, apply it
if [ ${BANDWIDTH_LIMIT} != 0 ]; then
    BANDWIDTH_LIMIT=${BANDWIDTH_LIMIT}*8
    BANDWIDTH_PARA="-l ${BANDWIDTH_LIMIT}"
fi

# Delete exist file from server before transfer
if [ ${DELETE_BEFORE_CP} -eq 1 ]; then
    echo ">> Deleting files before send.. ${FILE_DEL_LIST}"
    ssh -p ${SERVER_META} "rm -f ${FILE_DEL_LIST}"
fi

# Send file to server
SERVER_PORT="${SERVER_META%%\ *}"
echo ">> Sending files to server ${SERVER_NAME} .."
scp ${BANDWIDTH_PARA} ${PUBLIC_KEY} -P ${SERVER_PORT} ${FILE_SEND_LIST} ${SERVER_USER}@${SERVER_IP}:${TARGET_PATH}

