#!/bin/bash

function usage()
{
    cat << EOUSAGE
Usage: ssh-to [options] NICK_NAME
       -u USER: specify server user
       -p PORT: specify server port
EOUSAGE
}

# Name-to-ip mapping file
THIS_FOLDER="${0%/*}"
source "${THIS_FOLDER}/func/utility.func"

SERVER_USER=""
SERVER_PORT=""

while getopts ":u:p:" opt
do
    case ${opt} in
        u ) SERVER_USER="${OPTARG}"
            ;;
        p ) SERVER_PORT="${OPTARG}"
            ;;
        ? ) usage
            exit 1
            ;;
    esac
done
shift $((${OPTIND} - 1))

SERVER_NAME=${1}
shift 1

# Get server user name and IP
SERVER_META=`getServerMeta "d${THIS_FOLDER}" "n${SERVER_NAME}" "u${SERVER_USER}" "p${SERVER_PORT}"`
if [ "${SERVER_META}" == "" ]; then
    echo "[ERROR] Unknown server or wrong parameters."
    exit 1
fi

# Login to server
ssh -p ${SERVER_META}

