#!/bin/bash

function usage()
{
    cat << EOUSAGE
Usage: ssh-copy-id-to [options] SERVER_NAME
       -i FILE: specify ssh identity file
       -u USER: specify server user
       -p PORT: specify server port
EOUSAGE
}

# Name-to-ip mapping file
THIS_FOLDER="${0%/*}"
source "${THIS_FOLDER}/func/utility.func"

IDENTITY_FILE=`ls ${HOME}/.ssh/id_[rd]sa.pub | head -1`
SERVER_USER=""
SERVER_PORT=""

while getopts ":i:u:p:" opt
do
    case ${opt} in
        i ) IDENTITY_FILE=${OPTARG}
            ;;
        u ) SERVER_USER="${OPTARG}"
            ;;
        p ) SERVER_PORT="${OPTARG}"
            ;;
        ? ) usage
            exit 1
            ;;
    esac
done
shift $((${OPTIND} - 1))

SERVER_NAME=${1}
shift 1

# Get server user name and IP
SERVER_META=`getServerMeta "d${THIS_FOLDER}" "n${SERVER_NAME}" "u${SERVER_USER}" "p${SERVER_PORT}"`
if [ "${SERVER_META}" == "" ]; then
    echo "[ERROR] Unknown server or wrong parameters."
    exit 1
fi

# Check identify file exist and not empty
if [ "${IDENTITY_FILE}" == "" ]; then
    echo "[ERROR] Cannot find identity file, please specify use -i parameter."
    exit 1
fi
PUB_CREDENCE=`cat ${IDENTITY_FILE}`
if [ "${PUB_CREDENCE}" == "" ]; then
    echo "[ERROR] No identities found in ${IDENTITY_FILE}"
    exit 1
fi

# Copy identity key to server
echo ${PUB_CREDENCE} | ssh -p ${SERVER_META} "umask 077; test -d .ssh || mkdir .ssh ; cat >> .ssh/authorized_keys" || exit 1

# Done
echo "[Done] Now try login into the machine with \"ssh-to ${SERVER_NAME}\""

